package com.nlogneg.view;

import javax.swing.JFrame;

public class SetupPreferencesWindow extends JFrame{

	private static final long serialVersionUID = -5904357494242644808L;
	/** Creates new form SetupPreferencesFrame */
	public SetupPreferencesWindow() {
		initComponents();
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	private void initComponents() {

		bgPanel = new javax.swing.JPanel();
		shareFolderLocationPanel = new javax.swing.JPanel();
		shareFolderLocationLabel = new javax.swing.JLabel();
		shareFolderLocationField = new javax.swing.JTextField();
		shareFolderLocationButton = new javax.swing.JButton();
		bandwidthSettingsPanel = new javax.swing.JPanel();
		maxDownloadSpeedLabel = new javax.swing.JLabel();
		maxUploadSpeedLabel = new javax.swing.JLabel();
		maxDownloadSpeedField = new javax.swing.JTextField();
		maxUploadSpeedField = new javax.swing.JTextField();
		OKButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Setup Preferences");

		bgPanel.setName("bgPanel"); // NOI18N

		shareFolderLocationPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		shareFolderLocationPanel.setName("shareFolderLocationPanel"); // NOI18N

		shareFolderLocationLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		shareFolderLocationLabel.setText("Share Folder Location");
		shareFolderLocationLabel.setName("shareFolderLocationLabel"); // NOI18N

		shareFolderLocationField.setEditable(false);
		shareFolderLocationField.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		shareFolderLocationField.setName("shareFolderLocationField"); // NOI18N

		shareFolderLocationButton.setText("...");
		shareFolderLocationButton.setName("shareFolderLocationButton"); // NOI18N

		javax.swing.GroupLayout shareFolderLocationPanelLayout = new javax.swing.GroupLayout(shareFolderLocationPanel);
		shareFolderLocationPanel.setLayout(shareFolderLocationPanelLayout);
		shareFolderLocationPanelLayout.setHorizontalGroup(
				shareFolderLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(shareFolderLocationPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(shareFolderLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shareFolderLocationPanelLayout.createSequentialGroup()
										.addComponent(shareFolderLocationField, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(shareFolderLocationButton))
										.addComponent(shareFolderLocationLabel))
										.addContainerGap())
				);
		shareFolderLocationPanelLayout.setVerticalGroup(
				shareFolderLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(shareFolderLocationPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addComponent(shareFolderLocationLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(shareFolderLocationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(shareFolderLocationField, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(shareFolderLocationButton))
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);

		bandwidthSettingsPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
		bandwidthSettingsPanel.setName("bandwidthSettingsPanel"); // NOI18N

		maxDownloadSpeedLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		maxDownloadSpeedLabel.setText("Maximum Download Speed (Kilobytes/second)");
		maxDownloadSpeedLabel.setName("maxDownloadSpeedLabel"); // NOI18N

		maxUploadSpeedLabel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
		maxUploadSpeedLabel.setText("Maximum Upload Speed (Kilobytes/second)");
		maxUploadSpeedLabel.setName("maxUploadSpeedLabel"); // NOI18N

		maxDownloadSpeedField.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
		maxDownloadSpeedField.setName("maxDownloadSpeedField"); // NOI18N

		maxUploadSpeedField.setMinimumSize(new java.awt.Dimension(6, 21));
		maxUploadSpeedField.setName("maxUploadSpeedField"); // NOI18N
		maxUploadSpeedField.setPreferredSize(new java.awt.Dimension(6, 21));

		javax.swing.GroupLayout bandwidthSettingsPanelLayout = new javax.swing.GroupLayout(bandwidthSettingsPanel);
		bandwidthSettingsPanel.setLayout(bandwidthSettingsPanelLayout);
		bandwidthSettingsPanelLayout.setHorizontalGroup(
				bandwidthSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(bandwidthSettingsPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(bandwidthSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(maxDownloadSpeedLabel)
								.addComponent(maxDownloadSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addComponent(maxUploadSpeedLabel)
								.addComponent(maxUploadSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
								.addContainerGap(167, Short.MAX_VALUE))
				);
		bandwidthSettingsPanelLayout.setVerticalGroup(
				bandwidthSettingsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(bandwidthSettingsPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addComponent(maxDownloadSpeedLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(maxDownloadSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(maxUploadSpeedLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(maxUploadSpeedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				);

		OKButton.setText("OK");
		OKButton.setName("OKButton"); // NOI18N

		cancelButton.setText("Cancel");
		cancelButton.setName("cancelButton"); // NOI18N

		javax.swing.GroupLayout bgPanelLayout = new javax.swing.GroupLayout(bgPanel);
		bgPanel.setLayout(bgPanelLayout);
		bgPanelLayout.setHorizontalGroup(
				bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(bgPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
								.addComponent(bandwidthSettingsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(shareFolderLocationPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bgPanelLayout.createSequentialGroup()
										.addComponent(cancelButton)
										.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(OKButton)))
										.addContainerGap())
				);
		bgPanelLayout.setVerticalGroup(
				bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(bgPanelLayout.createSequentialGroup()
						.addContainerGap()
						.addComponent(shareFolderLocationPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(18, 18, 18)
						.addComponent(bandwidthSettingsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addGroup(bgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(OKButton)
								.addComponent(cancelButton))
								.addContainerGap())
				);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);
		layout.setVerticalGroup(
				layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(bgPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				);

		pack();
	}// </editor-fold>

	// Variables declaration - do not modify
	private javax.swing.JButton OKButton;
	private javax.swing.JPanel bandwidthSettingsPanel;
	private javax.swing.JPanel bgPanel;
	private javax.swing.JButton cancelButton;
	private javax.swing.JTextField maxDownloadSpeedField;
	private javax.swing.JLabel maxDownloadSpeedLabel;
	private javax.swing.JTextField maxUploadSpeedField;
	private javax.swing.JLabel maxUploadSpeedLabel;
	private javax.swing.JButton shareFolderLocationButton;
	private javax.swing.JTextField shareFolderLocationField;
	private javax.swing.JLabel shareFolderLocationLabel;
	private javax.swing.JPanel shareFolderLocationPanel;
	// End of variables declaration
}
